# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b55f3cf4713f7b1bbb0ffd02648b7e076c3dcd213f26a23719c30c359ff1ba1260da906d67cff7adcd8bbb1a07b8763aede083fb09061e59de57ff025a51bae

test:
  secret_key_base: f4472b0c0e7b5edc076459511c4d3350d895ae01ee3d01150b142fc390d0d3da0cab36dc44be33c8093329ed9015947f0959a620c9de80ed5a9c8683c6be125f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
